"""`scripts/README.md` must describe every script, in the script's own words.

A hand-maintained index of ninety-odd tools is wrong within a month: someone adds a
script and forgets the index, or edits a docstring and leaves the index describing the
old behaviour. Both failures are silent, and both make the index worse than useless —
a reader trusts it and is misled.

So the index is checked against the source rather than written beside it. These tests
read the real `scripts/README.md` and the real docstrings; adding a script without
listing it, or changing what a script says it does without updating the line, fails
here. The summaries are generated by the same `summarise` the tests use, so the two
cannot disagree.
"""

import ast
import re
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPTS = REPO / "scripts"
REGISTRY = SCRIPTS / "README.md"

#: Files with no docstring to read, so their line is written by hand and only
#: checked for presence.
NON_PYTHON = {
    "bootstrap_macos.sh": (
        "Create the project virtualenv and install the SF3D backend and its native "
        "dependencies (needs Python 3.10/3.11 and Homebrew's libomp)."
    ),
    "bootstrap_trellis_macos.sh": (
        "Clone and install the `shivampkumar/trellis-mac` port, with the Metal "
        "acceleration backends when Xcode's Metal compiler is present and a slower CPU "
        "bake fallback when it is not."
    ),
    "bootstrap_sf3d.ps1": (
        "Thin PowerShell wrapper for Stable Fast 3D setup on Windows."
    ),
    "bootstrap_pixal3d.ps1": (
        "Thin PowerShell wrapper for Pixal3D setup on Windows."
    ),
    "rebuild_metallib.sh": (
        "Recompile and install cumesh's Metal shader library after patching a `.metal` "
        "source, without rebuilding the Obj-C++ extension."
    ),
    "rebuild_mtlbvh_metallib.sh": (
        "Recompile and install only MtlBVH's Metal shader library after editing "
        "`bvh.metal`."
    ),
    "rebuild_mtlbvh_native.sh": (
        "Rebuild, install and ad-hoc sign MtlBVH's native extension. Stop every Python "
        "worker first: overwriting a loaded Mach-O image makes macOS kill them."
    ),
    "runpod_trellis2_cuda_requirements.txt": (
        "Pinned CUDA wheels for the RunPod control run; not used by any local path."
    ),
}


def summarise(path: Path) -> str:
    """The one-line summary for a script, taken from its own docstring.

    The first sentence of the first paragraph, minus a trailing em-dash aside or
    parenthetical — those carry the rationale, which belongs in the file, not in a
    table cell.
    """
    doc = ast.get_docstring(ast.parse(path.read_text())) or ""
    if not doc.strip():
        raise ValueError(f"{path.name} has no module docstring")
    flat = " ".join(doc.strip().split("\n\n")[0].split())
    sentence = re.match(r"(.+?\.)(\s|$)", flat)
    text = sentence.group(1) if sentence else flat
    text = re.split(r"\s+--\s+|\s+—\s+", text)[0]
    text = re.sub(r"\s*\([^()]*\)\s*\.?$", "", text)
    # The docstrings are reStructuredText; the registry is Markdown, where a double
    # backtick renders as a stray empty code span.
    text = text.replace("``", "`")
    return text.rstrip(".") + "."


def present_scripts() -> set[str]:
    """Every script the repository would ship: tracked, plus untracked and not ignored.

    Three definitions were possible and only this one is right. Tracked-only lets a
    brand-new script sit unlisted until someone stages it, which is exactly when a
    reader is most likely to meet it and wonder what it is. Everything-on-disk demands
    a registry line for deliberately local tools -- `scripts/image_gallery.py` is
    git-ignored because it hard-codes a tailnet address, and documenting it in a public
    README would be wrong. Honouring `.gitignore` draws the line where the repository
    already draws it.
    """

    def git(*args: str) -> set[str]:
        done = subprocess.run(
            ["git", *args, "scripts/"], cwd=REPO, capture_output=True, text=True, check=True
        )
        return {Path(line).name for line in done.stdout.split()}

    names = git("ls-files") | git("ls-files", "--others", "--exclude-standard")
    return {n for n in names if n != "README.md" and not n.startswith(".")}


def registry_entries() -> dict[str, str]:
    """Script name to summary, as the registry table rows spell them."""
    rows = re.findall(r"^\|\s*`([^`]+)`\s*\|\s*(.+?)\s*\|$", REGISTRY.read_text(), re.M)
    return dict(rows)


def test_the_registry_exists_and_is_not_empty():
    assert REGISTRY.exists(), "scripts/ needs a README a reader can start from"
    assert len(registry_entries()) > 50


def test_every_shipped_script_is_listed():
    """A new tool is not finished until a reader can find out what it is for."""
    missing = sorted(present_scripts() - set(registry_entries()))
    assert not missing, f"add these to scripts/README.md: {missing}"


def test_the_registry_lists_nothing_that_was_deleted():
    stale = sorted(set(registry_entries()) - present_scripts())
    assert not stale, f"remove these from scripts/README.md: {stale}"


def test_no_script_is_listed_twice():
    names = re.findall(r"^\|\s*`([^`]+)`\s*\|", REGISTRY.read_text(), re.M)
    duplicated = sorted({n for n in names if names.count(n) > 1})
    assert not duplicated, f"listed under more than one heading: {duplicated}"


def test_each_summary_still_matches_its_docstring():
    """Catches the quiet failure: the script changed, the index did not."""
    drifted = []
    for name, listed in registry_entries().items():
        if name in NON_PYTHON:
            continue
        actual = summarise(SCRIPTS / name)
        if listed != actual:
            drifted.append(f"{name}\n    registry: {listed}\n    docstring: {actual}")
    assert not drifted, "summaries have drifted from the source:\n" + "\n".join(drifted)


def test_hand_written_summaries_are_used_verbatim():
    entries = registry_entries()
    for name, expected in NON_PYTHON.items():
        assert entries.get(name) == expected, f"{name} must use its NON_PYTHON summary"


@pytest.mark.parametrize("name", sorted(p.name for p in SCRIPTS.glob("*.py")))
def test_every_python_script_has_a_docstring_to_summarise(name):
    assert summarise(SCRIPTS / name), f"{name} needs a module docstring"


def test_summaries_stay_short_enough_to_scan():
    too_long = {n: len(s) for n, s in registry_entries().items() if len(s) > 200}
    assert not too_long, f"these read as paragraphs, not table cells: {too_long}"


def test_summarise_trims_the_rationale_from_a_first_sentence(tmp_path):
    sample = tmp_path / "sample.py"
    sample.write_text('"""Do the thing -- which matters because of a long reason.\n\nBody.\n"""\n')
    assert summarise(sample) == "Do the thing."


def test_summarise_drops_a_trailing_parenthetical(tmp_path):
    sample = tmp_path / "sample.py"
    sample.write_text('"""Render a sequence at the locked angle (see docs/bake-spec.md)."""\n')
    assert summarise(sample) == "Render a sequence at the locked angle."


def test_summarise_joins_a_wrapped_first_sentence(tmp_path):
    sample = tmp_path / "sample.py"
    sample.write_text('"""Append a rigged character into the currently\nlive scene, positioned."""\n')
    assert summarise(sample) == "Append a rigged character into the currently live scene, positioned."


def test_summarise_converts_rest_literals_to_markdown_code(tmp_path):
    sample = tmp_path / "sample.py"
    sample.write_text('"""Generate through the ``trellis-space-mac`` port."""\n')
    assert summarise(sample) == "Generate through the `trellis-space-mac` port."


def test_summarise_rejects_a_script_with_no_docstring(tmp_path):
    sample = tmp_path / "sample.py"
    sample.write_text("import os\n")
    with pytest.raises(ValueError, match="no module docstring"):
        summarise(sample)
